Repository liamg/aminal, pull requests merged in 2019-01, with the labels that each got.

#133 Fix the bug when the application became unresponsible when minimizing
  gui/gui.go
Labels: bug

#134 Fix -ignore-config flag behavior
  config.go
Labels: bug

#132 Sixel Part 2. Ignore embedded by Windows CSI and OSC sequences.
  matrix/automatrix.go
  terminal/csi.go
  terminal/sixel.go
Labels: Windows

#137 Erase cell with default background colour
  buffer/buffer.go
  buffer/cell.go
Labels: bug

#136 Bug: mouse cursors leaks
  gui/gui.go
  gui/mouse.go
Labels: bug

#148 Changes to minimize memory allocations and to ensure OpenGL objects cleanup
  glfont/font.go
  glfont/truetype.go
  gui/fontmap.go
  gui/fonts.go
  gui/gui.go
  gui/renderer.go
Labels: bug

#156 Fix memory leaking
  buffer/buffer.go
Labels: bug

#163 Map input key codes to lower case
  gui/input.go
Labels: Windows, bug

#162 Vttest
  buffer/buffer.go
  buffer/buffer_test.go
  gui/gui.go
  gui/input.go
  gui/renderer.go
  main_test.go
  terminal/ansi.go
  terminal/csi.go
  terminal/modes.go
  terminal/output.go
  terminal/scr_state.go
  terminal/sgr.go
  terminal/terminal.go
  vttest/test-cursor-movement-1.png
  vttest/test-cursor-movement-2.png
  vttest/test-cursor-movement-3.png
  vttest/test-cursor-movement-4.png
  vttest/test-cursor-movement-5.png
  vttest/test-cursor-movement-6.png
Labels: vttest

#164 Do not trigger window resizing work if no change in dimensions
  gui/fonts.go
  gui/gui.go
Labels: bug

#184 Update loginshell to version with Windows support
  Gopkg.lock
  vendor/github.com/riywo/loginshell/loginshell.go
  vendor/github.com/riywo/loginshell/loginshell_test.go
Labels: Windows, bug

#181 Add "select with mouse to copy" / "right click to paste" functionality
  README.md
  buffer/buffer.go
  config/config.go
  config/defaults.go
  gui/gui.go
  gui/mouse.go
Labels: enhancement

#186 Fix issue: sometimes it cuts selected text when copying to clipboard
  buffer/buffer.go
  gui/actions.go
Labels: bug

#185 Make launching URLs on Windows work
  gui/gui.go
  platform/darwinLaunch.go
  platform/linuxLaunch.go
  platform/winLaunch.go
Labels: Windows, bug

#188 Fix the bug when carriage returns doubled on input
  buffer/buffer_test.go
  buffer/terminal_state.go
Labels: bug
