Repository liamg/aminal, pull requests merged in 2019-03, with the labels that each got.

#243 Include source branch title in nightly build tag
  ci/push-nightly-tag.sh
Labels: ci

#244 [travis] Insert new line after each git log commit message to be corr…
  .travis.yml
Labels: ci

#241 #217 rectangular select and copy
  buffer/buffer.go
  buffer/buffer_test.go
  gui/actions.go
  gui/gui.go
  gui/input.go
  gui/mouse.go
Labels: feature

#239 Add correct handling of attaching to child console errors
  platform/winpty.go
Labels: Windows, bug

#232 Add screenshot to validate 11th subtest of vttest "Screen feature" test suite
  main_test.go
  vttest/test-screen-features-11.png
Labels: ci

#240 Fix GL error GL_INVALID_OPERATION message (issue #153)
  glfont/truetype.go
Labels: bug

#246 #195 Real buffer clearing
  buffer/buffer.go
  config/actions.go
  config/defaults.go
  gui/actions.go
  platform/interfaces.go
  platform/unixpty.go
  platform/winpty.go
  terminal/terminal.go
Labels: Windows, feature

#247 Automatic updates on Windows
  .gitignore
  Makefile
  windows.md
  windows/Uninstaller.nsi
  windows/installer/AminalSetup.exe.manifest
  windows/installer/installer.go
  windows/launcher/launcher.go
  windows/launcher/versioninfo.json
  windows/winutil/winutil.go
Labels: Windows, feature

#248 Add option for generating CPU profile
  config.go
  config/config.go
  main.go
Labels: feature

#245 Avoid polling in main GUI loop
  buffer/buffer.go
  buffer/buffer_test.go
  gui/actions.go
  gui/gui.go
  gui/overlays.go
  terminal/notify.go
  terminal/output.go
  terminal/terminal.go
Labels: enhancement, feature

#260 Make shells running on Windows
  platform/winpty.go
Labels: bug, feature

#229 Implementation of the vertical scrollbar
  README.md
  buffer/buffer.go
  config/config.go
  config/defaults.go
  gui/fonts.go
  gui/gui.go
  gui/mouse.go
  gui/rectangleRenderer.go
  gui/renderer.go
  gui/scrollbar.go
  main.go
  main_test.go
Labels: feature

#262 Solve intermittent build errors
  gui/gui.go
  main.go
  main_test.go
Labels: Linux, bug, ci

#255 Fix windows launcher
  Makefile
  windows/launcher/launcher.go
Labels: Windows

#265 Smarter URL/URI parsing
  buffer/buffer.go
Labels: bug

#267 #116 URXVT extended mouse mode support
  gui/mouse.go
  terminal/modes.go
  terminal/terminal.go
Labels: feature

#271 Improve font rendering
  glfont/font.go
  glfont/truetype.go
  gui/fonts.go
  gui/gui.go
Labels: enhancement
